apiVersion: infra.contrib.fluxcd.io/v1alpha1
kind: Terraform
metadata:
  name: helloworld
  namespace: flux-system
spec:
  path: ./hello.tf
  sourceRef:
    kind: GitRepository
    name: manual-approve-test
  interval: 30s
  approvePlan: "plan-main-6ccc3fa63b2a1598b7b91a7aa7a0246c037b4bc3"
  storeReadablePlan: human
