apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: helloworld
  namespace: flux-system
spec:
  path: ./hello.tf
  sourceRef:
    kind: GitRepository
    name: manual-approve-test
  vars:
  - name: subject
    value: many_cats
  interval: 30s
  approvePlan: "plan-main-0fd556ccb4"
  storeReadablePlan: human
