---
apiVersion: infra.contrib.fluxcd.io/v1alpha1
kind: Terraform
metadata:
  name: helloworld
  namespace: flux-system
spec:
  path: ./hello.tf
  sourceRef:
    kind: GitRepository
    name: manual-approve-test
  interval: 30s
  approvePlan: ""
  storeReadablePlan: human
